config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: {scope: :list_id, message: "it is already in the list"}
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :lists, through: :bookmarks
  has_many :bookmarks
  validates :title, presence: true
  validates :overview, presence: true
  validates :title, uniqueness: true
end



#   should not be able to destroy self if has bookmarks children (FAILED - 19)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unproccessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit([:comment, :movie_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list  = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
    @lists = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unproccessable_entity
    end
  end

  def destroy
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="markbook--form mt-3">
    <%# <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn--green" %>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, label: false, prompt: "Add a movie" %>
      <%= f.input :comment, label: false, placeholder: "Add a comment" %>
      <%= f.button :submit, "Add Movie to List" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-Tw6DE7qO8bz2RrDjA2BBjc4yqeefFg6aMp9pma4Fz+gUqqTfQ6ENow5c/Qa2jRD5" crossorigin="anonymous" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar">

        <h1>🍿</h1>
        <div class="btns">
          <%= link_to "My lists", lists_path %>
          <%= link_to "New list", new_list_path %>

      </div>
        </div>
      <%= yield %>

  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <h1>Save any kind of movies</h1>
</div>
<div class="container">
  <div class="custom-flex mt-3 mb-3">
    <h3>My lists</h3>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn--green" %>
  </div>

  <div class="parent--box">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
    <div class="list--card">
      <h2><%= list.name %></h2>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Create new list</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>

    <%= f.submit %>
  <% end %>

  <div class="parent--box">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
    <div class="list--card">
      <h2><%= list.name %></h2>
    </div>
    <% end %>
    <% end %>
  </div>

</div>

app/views/lists/show.html.erb
<div class="banner--list">
  <div class="yellow--box">
    <p>
      <%= @list.movies.length %>
      movies
    </p>
  </div>
  <h1><%= @list.name %> movies</h1>
</div>
  <div class="container markbook--form mt-3">
    <%# <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn--green" %>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, label: false, prompt: "Add a movie" %>
      <%= f.input :comment, label: false, placeholder: "Add a comment" %>
      <%= f.button :submit, "Add Movie to List" %>
    <% end %>
  </div>
  <div class="container ">
  <div class="grid-movies">
    <% @list.movies.each do |movie|%>
      <div class="movie--card m-5">
        <img src="<%=movie.poster_url%>", id="poster">
        <div class="flex">
          <h3><%= movie.title %></h3>
          <h3 class="gray">•<%= movie.rating.to_f %></h3>
          <i class="fa-solid fa-star"></i>
        </div>
        <p><%= movie.overview %></p>

  <% bookmark = Bookmark.find_by(movie_id: movie.id, list_id: @list.id) %>

        <div class="last-options">
        <div>
         <i class="fa-solid fa-comment"></i>
         <%= bookmark.comment %>
        </div>
          <div class="">
          <%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger m-3' %></small>
          </div>
        </div>
      </div>
    <%end %>
    </div>

  </div>
</div>